spring:
  config:
    import:
      - classpath:/project_backend_security/application.yml
      - classpath:/project_backend_security/application-jwt.yml
      - classpath:/project_backend_security/application-kakao.yml