spring:
  profiles:
    active: local
    include: jwt, swagger

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/mokindangdb?useSSL=false&serverTimezone=Asia/Seoul&character_set_server=utf8mb4&allowPublicKeyRetrieval=true
    password: qwerqwer

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations:
        - classpath:data.sql

---

spring:
  config:
    activate:
      on-profile: ci

  jpa:
    hibernate:
      ddl-auto: validate

---

spring:
  config:
    activate:
      on-profile: deploy

  datasource:
    url: jdbc:mysql://mokindang-db.cla9o9xvetck.ap-northeast-2.rds.amazonaws.com:3306/mokindangdb?useSSL=false&serverTimezone=Asia/Seoul&character_set_server=utf8mb4&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: create
