INSERT INTO member (EMAIL, ALIAS, REGION)
VALUES ('test@email.com', '테스트유저', '동작구');
INSERT INTO board (MEMBER_ID, STARTING_DATE, ACTIVITY_CATEGORY, TITLE, CONTENT, REGION, ON_RECRUITMENT)
VALUES (1, '2023-3-15', '달리기', '제목', '본문내용', '2023-3-11', false);
