INSERT INTO member (EMAIL, ALIAS, REGION, PROFILE_IMAGE_URL, PROFILE_IMAGE_NAME)
VALUES ('test@email.com', '테스트유저', '동작구', 'DEFAULT_PROFILE_IMAGE_URL', 'DEFAULT_PROFILE_IMAGE_NAME');
INSERT INTO recruitment_board (MEMBER_ID, CREATING_DATE_TIME, STARTING_DATE, ACTIVITY_CATEGORY, TITLE, CONTENT_BODY, REGION, ON_RECRUITMENT)
VALUES (1,'2023-3-9-12-0', '2023-3-15', 'RUNNING', '제목', '본문내용', '동작구', false);
