# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: 
    - main
    - dev
    - feature/*
    
  pull_request:
    branches: 
      - main
      - dev
      - feature/*
    
permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      
      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          character set server: 'utf8mb4'
          collation server: 'utf8mb4_general_ci'
          mysql version: '8.0.31'
          mysql database: 'mokindangdb'
          mysql user: 'root'
          mysql password: 'qwerqwer'
          
      - name: docker status
        run: sudo docker ps -a

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew     

      - name: Build with Gradle
        run: ./gradlew build

      - name: docker status
        run: sudo docker ps -a

